name: Build Android APK

# این ورکفلو زمانی اجرا می‌‎شه که روی شاخه main تغییری push بشه
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # سیستم عامل سرور برای اجرای بیلد

    steps:
    # مرحله ۱: دریافت سورس از ریپازیتوری
    - name: Checkout code
      uses: actions/checkout@v3

    # مرحله ۲: نصب JDK نسخه ۱۷ برای اجرای Gradle
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # مرحله ۳: دادن مجوز اجرا به فایل gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # مرحله ۴: بیلد اپ با Gradle
    # برای نسخه دیباگ می‌تونی assembleDebug رو جایگزین assembleRelease کنی
    - name: Build Release APK
      run: ./gradlew assembleRelease

    # مرحله ۵: آپلود خروجی APK برای دانلود از بخش Actions > Artifacts
    - name: Upload built APK
      uses: actions/upload-artifact3
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk
